import React, { useEffect, useState } from 'react';
import { Link } from "react-router-dom";
import axios from 'axios';
import jsPDF from 'jspdf';

function Patients() {
    const [patients, setPatients] = useState([]);
    const [searchTerm, setSearchTerm] = useState('');

    useEffect(() => {
        axios.get('http://localhost:3001')
            .then(result => setPatients(result.data))
            .catch(err => console.log(err));
    }, []);

    const handleDelete = (id) => {
        axios.delete('http://localhost:3001/deletePatient/' + id)
            .then(res => {
                console.log(res);
                window.location.reload();
            })
            .catch(errr => console.log(errr));
    };

    const downloadRecordAsPDF = (patient) => {
        const pdf = new jsPDF();

        // Add background color
        pdf.setFillColor("#fff");
        pdf.rect(0, 0, 110, 297, 'F'); // A4 page size

        // Add title
        pdf.setTextColor("#000000");
        pdf.setFontSize(18);
        pdf.text("Channeling Information - Schedule Report", 105, 20, { align: 'center' });

        // Add user details
        pdf.setFontSize(12);
        pdf.text(`Name: ${patient.name}`, 20, 40);
        pdf.text(`Number: ${patient.number}`, 20, 60);
        pdf.text(`Email: ${patient.email}`, 20, 80);

        pdf.text(`Gender: ${patient.gender}`, 20, 100);
        pdf.text(`Age: ${patient.age}`, 20, 120);
        pdf.text(`Date: ${patient.date}`, 20, 140);
        

        // Add footer
        pdf.setTextColor("#808080");
        pdf.setFontSize(10);
        pdf.text("Generated by Care central Scheduling", 105, 280, { align: 'center' });

        pdf.save(`${patient.name}.pdf`);
    };
    
    const filteredPatients = patients.filter(patient =>
        patient.name.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <div className="d-flex vh-100 justify-content-center align-items-center" style={{ backgroundColor: '#fff' }}>
            <div className='w-90 rounded p-4' style={{ backgroundColor: '#e9ecef' }}>
            <Link to='/CreatePatients' className='btn btn-light rounded-2' style={{ backgroundColor: '#001f3f'}}><h6 style={{ color: 'white' }}>Add a channel</h6></Link>
                <br /><br />

                <input
                    type="text"
                    placeholder="Search by drug name"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    style={{
                        padding: '10px',
                        borderRadius: '5px',
                        border: '1px solid #ccc',
                        boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.1)',
                        width: '100%',
                        marginBottom: '10px' // Adjust this value to add spacing between the input field and the table
                    }}
                />
                <br></br><br></br>
                <table className="table table-striped">
                    <thead>
                        <tr>
                            <th className="col">Name</th>
                            <th className="col">Number</th>
                            <th className="col">Email</th>
                           
                            <th className="col">Gender</th>
                            <th className="col">Age</th>
                            <th className="col">Date</th>
                            <th className="col">Action</th>
                           
                        </tr>
                    </thead>
                    <tbody>
                        {filteredPatients.map((patient) => (
                            <tr key={patient._id}>
                            
                                <td>{patient.name}</td>
                                <td>{patient.number}</td>
                                <td>{patient.email}</td>
                                
                                <td>{patient.gender}</td>
                                <td>{patient.age}</td>
                                <td>{patient.date}</td>
                               

                                <td style={{ display: "flex", justifyContent: "space-between" }}>
    
    <Link to={`/update/${patient._id}`} className='btn btn-light rounded-2' style={{ backgroundColor: '#001f3f'}}><h6 style={{ color: 'white' }}>Update</h6></Link>
    <button style={{ marginLeft: "10px" }} className="btn btn-primary" onClick={(e) => handleDelete(patient._id)}>Delete</button>
    <button style={{ marginLeft: "10px" ,backgroundColor: '#001f3f'}} className="btn btn-light" onClick={() => downloadRecordAsPDF(patient)}><h6 style={{ color: 'white' }}>Download as PDF</h6></button>
</td>



                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}

export default Patients;
